def plot_acc_loss(history1, history2, history3, history4):
    fig = plt.figure(figsize=(10,5))
    plt.subplot(1, 2, 1)
    plt.plot(history1['val_dice_coefficient'])
    plt.plot(history2['val_dice_coefficient'])
    plt.plot(history3['val_dice_coefficient'])
    plt.plot(history4['val_dice_coefficient'])
    plt.title('model accuracy')
    plt.ylabel('dice coeff')
    plt.xlabel('epoch')
    plt.legend(['att_r2_unet_plus_val', 'att_unet_plus_val', 'r2_unet_plus_val', 'unet_plus_val' ], loc='upper right')
 
    plt.subplot(1, 2, 2)
    plt.plot(history1['val_loss'])
    plt.plot(history2['val_loss'])
    plt.plot(history3['val_loss'])
    plt.plot(history4['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['att_r2_unet_plus_val', 'att_unet_plus_val', 'r2_unet_plus_val', 'unet_plus_val'], loc='upper right')
    plt.show()
 
history1=np.load('/content/gdrive/My Drive/Nucleus Data/att_r2_unet_plus/att_r2_unet_plus_16.npy',allow_pickle='TRUE').item()
history2=np.load('/content/gdrive/My Drive/Nucleus Data/att_unet_plus/att_unet_plus_16.npy',allow_pickle='TRUE').item()
history3=np.load('/content/gdrive/My Drive/Nucleus Data/r2_unet_plus/r2_unet_plus_16.npy',allow_pickle='TRUE').item()
history4=np.load('/content/gdrive/My Drive/Nucleus Data/unet_plus/unet_plus_16.npy',allow_pickle='TRUE').item()
plot_acc_loss(history1, history2, history3, history4)
